### ISSUE TITLE
Scraper export to Google Drive disabled

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/lc-webscraping#46]
I am in Episode 4, when I get to this line: "and we can use the export functions to either create a Google Spreadsheet with the results", I clicked the Scraper button labelled 'Export to Google Docs...'
I chose my Google account then saw this error:

"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

Is anyone else having this problem?

**Comment by timtomch** [comment]
Indeed, this seems to be a problem with Scraper. Thanks for bringing this up. Maybe we should remove the mention of this option for now.

**Comment by timtomch** [comment]
I'm going to close the issues for now, but this points to a deeper problem with the Scraper extension, which has not been updated since 2015. The lesson should be updated with a more current tool.

@kimpham54 and I are scheduling a sprint in early December to rework this lesson. @PhilReedData, we welcome all input if you are interested in helping out!
